### ISSUE TITLE
installation error when running setup.sh

### ISSUE THREAD

**Issue by franok** [franok/uu-notify#9]
affected versions of uuNotify: v1.1.3 (and higher)

# Issue description:

Installation using the `setup.sh` script fails during `npm clean-install` step with following error:

```
Running 'npm clean-install' ...
npm WARN prepare removing existing node_modules/ before installation
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/mapbox/node-sqlite3.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
...
``` 

# Root cause
A mix of npm v6 git dependency url resolution (ssh instead of https) and a workaround to get over a too old version of node-gyp in sqlite3 version 5.0.2. Won't go into details here.

The update of node-gyp in sqlite3 [was already committed](https://github.com/mapbox/node-sqlite3/tree/3fb3715c4e699ca3bc19e47b136758c66f61e477), but not yet packed into a new release of sqlite3. So there was the need to install sqlite3 from the git project directly, causing the issue described above.

### Long term solution
update sqlite3 dependency, as soon as there is a new release of it on the npm registry, including the mentioned commit.

# Workaround

Run 2 commands, one before, and one after `./setup.sh`:
```
git config --global url."https://git@github.com".insteadOf ssh://git@github.com
./setup.sh
git config --global --remove-section url."https://git@github.com"
```
As you can see, this workaround requires changing a global git config. **To avoid unwanted side-effects, you want to change this back** with the second command, directly after `setup.sh` has completed!

**Comment by franok** [comment]
if `mapbox/node-sqlite3` is not updated any time soon, here are some alternative (long term) solutions:

from mapbox/node-sqlite3/issues/1493 :

#### A.) 
[modify package.json](https://github.com/mapbox/node-sqlite3/issues/1493#issuecomment-905633454):
```
"resolutions": {
  "node-gyp": "^8"
}
```
...and go back to latest mapbox/node-sqlite3 release

#### B.)
[replace mapbox/node-sqlite3 by the fork from microsoft-vscode guys](https://github.com/mapbox/node-sqlite3/issues/1493#issuecomment-978912655):
https://www.npmjs.com/package/@vscode/sqlite3
https://github.com/microsoft/vscode-node-sqlite3

--> use npm alias:
```
"sqlite3": "npm:@vscode/sqlite3@^5.0.7",
```
⚠️ the fork depends on Python >= 3.6.0

Todo:
- [ ] double check if this fork really uses an up-to-date version of node-gyp

---

Option B should be evaluated if it, because mapbox/node-sqlite3 seems to be not actively maintained (currently 300+ open issues and complaints about (transitive) vulnerabilities not being fixed timely)

**Comment by franok** [comment]
if `mapbox/node-sqlite3` is not updated any time soon, here are some alternative (long term) solutions:

from [mapbox/node-sqlite3, issue no.1493](mapbox/node-sqlite3/issues/1493): //how to avoid mentioning this issue in sqlite3-1493?

#### A.) 
[modify package.json](https://github.com/mapbox/node-sqlite3/issues/1493#issuecomment-905633454):
```
"resolutions": {
  "node-gyp": "^8"
}
```
...and go back to latest mapbox/node-sqlite3 release

#### B.)
[replace mapbox/node-sqlite3 by the fork from microsoft-vscode guys](https://github.com/mapbox/node-sqlite3/issues/1493#issuecomment-978912655):
https://www.npmjs.com/package/@vscode/sqlite3
https://github.com/microsoft/vscode-node-sqlite3

--> use npm alias:
```
"sqlite3": "npm:@vscode/sqlite3@^5.0.7",
```
⚠️ the fork depends on Python >= 3.6.0

Todo:
- [ ] double check if this fork really uses an up-to-date version of node-gyp

---

Option B should be evaluated if it, because mapbox/node-sqlite3 seems to be not actively maintained (currently 300+ open issues and complaints about (transitive) vulnerabilities not being fixed timely)

**Comment by franok** [comment]
new versions of sqlite3 [have been released](https://github.com/TryGhost/node-sqlite3/releases). however, with sqlite v5.0.8, uu-notify will crash at runtime on uberspace with following error:
```bash
$ node index.mjs
internal/modules/cjs/loader.js:1144
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/dummy-user/uu-notify/node_modules/sqlite3/lib/binding/napi-v6-linux-glibc-x64/node_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/fnk/uu-notify/node_modules/sqlite3/lib/sqlite3-binding.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}

```

needs further investigation
